[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "fab23cb9395aeca222f2f34f8db5945972f37d92"
lazy = true
mpi = "mpich"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "812202ee770b4881f0f7aa8d7195871d51c94055942f0b36d31811dfc42e3a06"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "74d8c2b6f5d3e870c2b5a17d86f9dcb2d1304399"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "76af9ecc49aab18abf199b1d7f4d913abfb667f518e826d74431c576bd03bc69"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "b0b5d89f6cd1c0471282972a104d7442841f9d31"
lazy = true
mpi = "openmpi"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "75115fe3e996996d7aba4b970b675aa7d94e9b8fdcd19bea73189b96bb2f054e"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78b6be75d96f2e0bbb46461a6b54b87fe0755ac5"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "2d511752db4cb22907ccc7a0f685d0c2270a138900c10b401ce004a61ebd5e98"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19bfd08be6356fa49bbac7949302b32db9f32e09"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "e9d408d4f2b3594cde2257c5246a3c5fb7c02917458c33b6ea491bf9486ed589"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28b886f2c52b8eb36f43529dffdf29e5b763440a"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "51b873a7a48a93f6a5a82a6db18b5a62496308a3553d07454543a81267c779b5"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8350004f23245458eae3ef93d38a4406b9a04e7a"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "f346d060240b0e80986bc357df343da212d82a69c6e4806f8b29edc9a024a4b0"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a0fe1b4f2f754136fd8e6baaba466a1f596e7b7"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "9a1d1157b48ea98d3b15b23e1e8d825d24d0f6dde5ec88847e29d8e956d75b6a"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "4822c83f425b8c524794a7c209e9fd5b46847b1c"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "1f526b095f7703dec15f26724df0553ed255a34078188c4779367b579b505c38"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "15f8716a4ea26c1a1ca1688fee535e9a9df8224c"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "b1637373452dacca2bac802a45588d9e36df98eccc8cc509db5d80d291761fb9"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "60e7a6171093edee710bf65162b9f6413e1d61ca"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "d9a18c994f0d413a3ca92166ed48a6f822a1e570e4688150720fb2b846882a04"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de902a9aac1bee8cec7b406a8261797d51429bae"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "a4f251793dfa277947d9f1718b1cccfc1eca25bc7ec9f81111f4c77a22e92d83"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5369e1d88b4ebcd6c7b948816d33321cb16c4d43"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "974c9cc60e20489b4a102609d859908b21c406c7ed2f8f75004ae297458ab913"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9d9efa959d1d2bb090c1bbaa61ebe5a1c8d8fbf"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "d0d00b24964e9dda671bae7d9b91cf3fbaf061127a1d0747d3976994795f5411"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c6a4cc5eeb3ee4fec9977ad0f04395af4a57572"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "fabe445e634f566b24fba1c7a20a019d66f1acf509ea0390b8deaba840900f07"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.riscv64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4e16bf40c2b2911b470650370556592e71e7d01"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "1277d274e6088123a35292eb952d3c84408e9774988fc589ec2883247c02e119"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.riscv64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "474e926e85da593ec6da71f5c8e6189b025db4a7"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "7996eb1288ed675046f2098685539e62f109d48de2181605bd35cf43f639f8f4"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.riscv64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "345256c6412bdf73bdc61292b4951fefadda7ecd"
lazy = true
mpi = "mpich"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "8f99a9739eb354f67e8796faf9ade8e2afe287157074900507391efb5f8533bf"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "ea77b8264b150566c05a7713f9820b0fb6c29235"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "3ee6c318c63d90989bb4df557a3ef39e5de19d35707ddc899af5275a011f17c6"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "8cafda66e3ab0b29ef7a1c4b92b9dd24122236da"
lazy = true
mpi = "openmpi"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "55a160e6e53b5a404284db026b72cea5e40df2892e4a951dcecfcbeb6b256261"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c9355b6d92ba9a92a2d561fb89b62c5d751ae10"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "cd5d1c2d2569110fd9c273370dd2569db63ee0f32aea1fc1498516c62353d719"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12357242b170117949570262e627330063c80b9a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "530af15023e0051e9b1a1b3d180cfd5b5c24e06d665823be98e7afccb5a81fd2"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3acc80cdc8890d54400607a6de1131fd19648b39"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "b62cd686e861b9b60c0fd068b95d2a93c247680b28d35c74246cd9fa3ee35dd1"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "803dc227fed3e296293e717bb369d7647e5ee0d6"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "998c5db4b281776948411c0aac08973fe4d1f77a9af75c80fdce7ace34076d8e"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a4f906629b36ce88717ac347678306704f43189"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "2e469e69ff7d0648b427430efa957a3c57c0719fe15b5c99490a9744fde9ef6d"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "de9a863e22d8f44d78f873e7b0acbc9e25e2cf4e"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "07bbf677e6bc0473c3bd53be82d58e89f9190f980ac841429c0e615448a3e40e"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "9ea2428a7af6bb630f57d345167c4346930083cf"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "51f97ea030324aa94008ac9cc0b8cdcc5b7b17cd5d17ca6cadf20f23121b8acb"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "88717a0ded69e12157ed3147b449354f8843bd23"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "0e15c6fa306b09128450ecd27d7ad86c5bca384a233bae3f51b8acda1a097957"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
