[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "9a45ab20bb2ec91f53a8a1503ae7c1b1f4374c9d"
lazy = true
mpi = "mpich"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "af249f7a89df02ce3fa8a5186e71b77720c3086be4904ae6253fd80e9b406579"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "870bccb5bbe689db0b7f46a8976c2b5b7c387714"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "5b588cb3ad4dd159c8a8766f16d373c50ce16a8e7053d0dad29330f953f550f0"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "d1ade8b8cbee2645f19dc20916bf4f4cd050caf8"
lazy = true
mpi = "openmpi"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "1afe3fed84c242ffc6adc0594f9a2adf719181dd40505fa8fb401e8833c6a317"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3076474588682f3ed4fbd0439c8937a115b8d1e"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "f019d6e582961ab8b927703264be878e99d309e25c9254522ecae99740e8c083"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6b2050fc3e08c28cd19709ddfc6c965e25cfdff"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "258413f8585c4122c82646b5c47d202544b14f066f386401d55a5e555474446a"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fa3857dc8df060d2226806c10ca5e365f5930cd"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "6110f1faeadd51dfeb5b725a70ffcea0b72ce0d770ecc55eeb064a109ddbe69a"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4db36ab46239e78122f966a66e51d0b96f921954"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "dcf1d4e838f43f2499337cc1bd6c97d01223f0f2e62f974166a4dff02105d49c"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10e59f44ce48d707dec0258c4b7ae0226508f217"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "0a6bf59e0e91b65ba3363b27572ef542eca90a73c1b2ffab8ebc257a83b8dc09"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "3ec25ea90e4281f51a79b6b50bdfa318ed23ea6b"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "3b00a179ece92ddc4b00af92b787add488fb65409a5eea76b9eece0d9f34f978"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "bb4aafe9386df2e5d3a0cbfd61d71d10ff6e9134"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "ed6192d5eda917ed0e02d276e5372d2a74e3e5b9640e3b75a73fb096f0154010"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "6e5c15e2f397b68c0967003681acb204471ac0d3"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "c120295086afde2fbe43003591f873fb6629edf17da21423faffb3692a2bb04f"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "654b67afacf12ebe6944a1f35d25395ef9d26d05"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "8185c5d28ed9f536e0c75f65cab00007e08aefe40552742f85ce9612b9a8b601"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "051cf3cffb30dd3407754758c559bf389cdcf966"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "55ba90a4748b4e3ddaa703c5b82b41891c6ed6223ef81dceac147789481f3c1f"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6125a74adf743b100db568311d1cacb54fd23d6"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "921a98d7cbb84951221a37df2a70a6149b60abb376facf10d123a7944a819d4b"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9a810396557049727bfaf51ad95e7033bcd4dca"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "f1dd43332497e773e5b5b4a32b5a5906c7d2e037c1894abda18ad9dbd9f5da18"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.riscv64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f0a9ed74811f340081d470131c1ae4b490aaa59"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "bc07207cd570e2326889b115a2733289ab0d382402e695ec2f7748550237fe57"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.riscv64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd2c2b2f44b1d736f306ed777a98399e9cee28c5"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "2d82808be13b1fefd9feac1aa291224aefdd16a722e89ca06072a59a9a98c353"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.riscv64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "26eb397a145980fe347b3a2c0186f44531111d35"
lazy = true
mpi = "mpich"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "01bf6de99e613e4702986a03b499c7162213b4acd97064b79432b5e8b0ad423f"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "a4f5fbcee38ff7100302c33eadd91959026e8918"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "613415b2cf7cc685ba22e83c12608b5a5eace6ac013a9c67cbf5708afe560b38"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "1959b78faee3d813e4238929fd4325c0309de831"
lazy = true
mpi = "openmpi"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "38e3f9abfa8caa0cbd67e60594755a2cfa3ce6d70bf4c91937ba1ef7b980b6e9"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f80d847b5466dbbb786d1a275f8efc193c4736ae"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "45dc373a7ebfb9c9913799b170f135ecbe77900c71e4932030871090514fdc14"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca1c13339583cdd87201689cdbd3d00a3c1e1750"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "8a23daf0dd62682b0e6d9cdd8dd685eb3b4001b9ca2e6b59457e8960989123e4"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a051dc3de195d0756c47a62e1d8dc4b314ab1721"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "df4aef7274b87a7b6e53ba2721e6c8646e3a9af39db7add288558e9da0a7b460"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d49cda9c513b323da51c64dbd1df0d44c807513f"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "d785cb9feb8bf79e1c545022e0d909c5ae5ad38017fb9080bc4b0c3c810578de"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00420b31bfe3e6b325e106073b452bc77f0938fd"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "8d3b69a7bcb54d839022152fa5a0a025ab2df1b09a61469441a5e1d389f5e19f"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "5f2d463ede810de9fd70526e7ed831572818ba07"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "5e9c1cc4325374f47db71f52ac4db9b6f73cc593d62a5e36fb7b48be20373364"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "475e060542358823f84ac8d3423fb4b9c51d90f1"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "90f738b5912f19f1b2de7c9c2b93a6e958b2d79eb4b08d9c7e5aa3d8e2647c35"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "b1de791b55b4b1136f115a96787682ccf949ad7d"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "899e0b97081fcf6577e04a1441ff66e875cc0780d2616f5fb8e5fd0eb0585d53"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.1+0/ADIOS2.v201.1100.1.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
