name = "ADIOS2_jll"
uuid = "44b1415a-b224-5c99-9168-ff4febb5f37f"
version = "201.1100.1+0"

[deps]
MicrosoftMPI_jll = "9237b28f-5490-5468-be7b-bb81f5f5e6cf"
OpenMPI_jll = "fe0851c0-eecd-5654-98d4-656369965a5c"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
pugixml_jll = "ef860afa-341e-548b-93de-15e6b165854a"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
zfp_jll = "007be453-5351-5f08-b8c7-bf95923b8de2"
yaml_cpp_jll = "01fea8cc-7d33-533a-824e-56a766f4ffe8"
HDF5_jll = "0234f1f7-429e-5d53-9886-15a909be8d59"
MPICH_jll = "7cb0a576-ebde-5e09-9194-50597f1243b4"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
Blosc2_jll = "d43303dc-dd0e-56c6-b0a8-331f4c8c9bfb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
protoc_jll = "c7845625-083e-5bbe-8504-b32d602b7110"
MGARD_jll = "55d5437f-3252-567d-b53c-03ff263d9b41"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
MPItrampoline_jll = "f1f71cc9-e9ae-5b93-9b94-4fe0e1ad3748"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
ZeroMQ_jll = "8f1865be-045e-5c20-9c9f-bfbfb0764568"
Zstd_jll = "3161d3a3-bdf6-5164-811a-617609db77b4"
Libffi_jll = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"

[compat]
MPIPreferences = "0.1"
Libdl = "< 0.0.1, 1"
pugixml_jll = "1.14.1"
LazyArtifacts = "< 0.0.1, 1"
zfp_jll = "1.0.2"
yaml_cpp_jll = "0.8.1"
HDF5_jll = "2.0.0"
JLLWrappers = "1.7.0"
MPICH_jll = "4.3.0 - 4"
Bzip2_jll = "1.0.9"
Blosc2_jll = "202.2200.0"
Artifacts = "< 0.0.1, 1"
julia = "1.6"
MGARD_jll = "1.6.0"
libpng_jll = "1.6.47"
MPItrampoline_jll = "5.5.3 - 5"
TOML = "< 0.0.1, 1"
ZeroMQ_jll = "4.3.6"
Libffi_jll = "~3.4.7"
OpenMPI_jll = "4.1.8, 5.0.7"
